<?php
$this->title = "Projects";
$this->headTitle($this->title);
?>
<div class="subHeaderContainer">
	<div class="subHeader">View Projects</div>
</div>
<div class="table">
	<form name="projectAddForm" id="projectAddForm" method="post"
		action="projects/add">
		<div class="rowHead">
			<div class="colsHead widthLargeHead">Project Name</div>
			<div class="colsHead widthMediumHead">Project Type</div>
			<div class="colsHead widthMediumHead">Current Milestone</div>
			<div class="colsHead widthMediumHead">Start Date</div>
			<div class="colsHead widthMediumHead">Tentative End date</div>
			<div class="colsHead widthMediumHead">Status</div>
			<div class="colsHead widthSmallHead">Action</div>
		</div>
		<?php foreach ($this->projects as $project) : ?>
		<div class="row" id="row_<?php echo $this->escape($project->id); ?>">
			<div class="cols widthLarge">
				<?php echo $this->escape($project->projectName); ?>
			</div>
			<div class="cols widthMedium">
				<?php echo $this->escape($project->projectType); ?>
			</div>
			<div class="cols widthMedium">
				<?php echo $this->escape($project->currentMilestone); ?>
			</div>
			<div class="cols widthMedium">
				<?php echo $this->escape($project->startDate); ?>
			</div>
			<div class="cols widthMedium">
				<?php echo $this->escape($project->startDate); ?>
			</div>
			<div class="cols widthMedium">In Progress</div>
			<div class="colsAction widthSmall">
				<a href="projects/edit">Edit</a>
			</div>
			<div class="colsAction uiCloseButton widthSmall"></div>
		</div>
		<?php endforeach; ?>
		<br />
		<div class="buttonContainer">
			<input type="button" class="blueButton" name="addProjectButton"
				id="addProjectButton" value="Add Project" />
		</div>
		<!--
		<div id="dialog-delete-project" title="Remove project">
			<p>
				<span class="ui-icon ui-icon-alert"
					style="float: left; margin: 0 7px 20px 0;"></span>This item will
				be permanently deleted and cannot be recovered. Are you sure?
			</p>
		</div>
 -->
		<!-- Add Project Dialog box -->
		<div id="dialog-form" title="Add new project">
			<fieldset>
			<div class="dialog-form-row">
				<div class="form-label"><label for="projectName">Project Name</label></div>
				<div class="form-field"><input type="text" name="projectName" id="projectName" class="" /></div>
			</div>
			<div class="dialog-form-row">
				<div class="form-label"><label for="projectType">Project Type</label></div>
				<div class="form-field"><input type="text" name="projectType" id="projectType" value="" class="" /></div>
			</div>

			<div class="dialog-form-row">
				<div class="form-label"><label for="status">Status</label></div>
				<div class="form-field">
					<select name="status" id="status">
                          <option value="1">In progress</option>
                          <option value="2">On Hold</option>
                          <option value="3">Completed</option>
                    </select>
				</div>
			</div>

			<div class="dialog-form-row">
				<div class="form-label"><label for="startDate">Start Date</label></div>
				<div class="form-field"><input type="text" name="startDate" id="startDate" value="" class="" /></div>
			</div>
			<div class="dialog-form-row">
				<div class="form-label"><label for="endDate">End Date</label></div>
				<div class="form-field"><input type="text" name="endDate" id="endDate" value="" class="" /></div>
			</div>

			<div class="dialog-form-row">
				<div class="form-label"><label for="users">Users</label></div>
				<div class="form-field">
					<select name="users" id="users" multiple="multiple" size="3">
                          <option value="1">Volvo</option>
                          <option value="2">Saab</option>
                          <option value="3">Mercedes</option>
                          <option value="4">Audi</option>
                          <option value="5">Audi</option>
                          <option value="6">Audi</option>
                    </select>
				</div>
			</div>

			<div class="dialog-form-row">
				<div class="form-label-textarea"><label for="description">Description</label></div>
				<div class="form-field"><textarea name="description" id="description" class=""></textarea></div>
			</div>

		</fieldset>
		</div>
	</form>
	<div class="spacer"></div>
</div>
<br />
