<?php
$this->title = "Projects";
$this->headTitle($this->title);
?>
<div class="subHeaderContainer">
	<div class="subHeader">View Projects</div>
</div>
<div class="table">
	<div class="rowHead">
		<div class="colsHead widthLargeHead">Project Name</div>
		<div class="colsHead widthMediumHead">Project Type</div>
		<div class="colsHead widthMediumHead"></div>
		<div class="colsHead widthMediumHead">Start Date</div>
		<div class="colsHead widthMediumHead">Tentative End date</div>
		<div class="colsHead widthMediumHead">Status</div>
		<div class="colsHead widthSmallHead">Action</div>
	</div>
	<?php foreach ($this->projects as $project) : ?>
	<div class="row" id="row_<?php echo $this->escape($project->id); ?>">
		<div class="cols widthLarge">
			<?php echo $this->escape($project->projectName); ?>
		</div>
		<div class="cols widthMedium">
			<?php echo $this->escape($project->projectType); ?>
		</div>
		<div class="cols widthMedium">
		</div>
		<div class="cols widthMedium">ddddd
			<?php echo $this->escape($project->startDate); ?>
		</div>
		<div class="cols widthMedium">
			<?php echo $this->escape($project->startDate); ?>
		</div>
		<div class="cols widthMedium">In Progress</div>
		<div class="colsAction widthSmall">
			<a href="<?php echo $this->escape($project->id); ?>/releases/view">View</a>
			<a href="projects/edit">Edit</a>
		</div>
		<div class="colsAction uiCloseButton widthSmall"></div>
	</div>
	<?php endforeach; ?>
	<br />

	<div class="buttonContainer">
		<input type="button" class="blueButton" name="addProjectButton"
			id="addProjectButton" value="Add Project" />
	</div>

	<!--
		<div id="dialog-delete-project" title="Remove project">
			<p>
				<span class="ui-icon ui-icon-alert"
					style="float: left; margin: 0 7px 20px 0;"></span>This item will
				be permanently deleted and cannot be recovered. Are you sure?
			</p>
		</div>
 -->
	<!-- Add Project Dialog box -->
	<div id="dialog-form" title="Add new project">
		<form name="projectAddForm" id="projectAddForm" method="post"
			action="projects/add">
			<fieldset>
				<div class="dialog-form-row">
					<div class="form-label">
						<label for="projectName">Project Name</label>
					</div>
					<div class="form-field">
						<input type="text" name="projectName" id="projectName" class="" />
					</div>
				</div>
				<div class="dialog-form-row">
					<div class="form-label">
						<label for="projectType">Project Type</label>
					</div>
					<div class="form-field">
						<select name="projectType" id="projectType">
							<?php foreach ($this->projectTypes as $projectType):?>
								<option value="<?php echo $projectType['id'];?>"><?php echo $projectType['type'];?></option>
							<?php endforeach;?>
						</select>
					</div>
				</div>
				<div class="dialog-form-row">
					<div class="form-label">
						<label for="status">Status</label>
					</div>
					<div class="form-field">
						<select name="status" id="status">
							<?php foreach ($this->statuses as $status) : ?>
							<option value="<?php echo $status['id']; ?>">
								<?php echo $status['status']; ?>
							</option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
				<div class="dialog-form-row">
					<div class="form-label">
						<label for="startDate">Start Date</label>
					</div>
					<div class="form-field">
						<input type="text" name="startDate" id="startDate" value=""
							class="" />
					</div>
				</div>
				<div class="dialog-form-row">
					<div class="form-label">
						<label for="endDate">End Date</label>
					</div>
					<div class="form-field">
						<input type="text" name="endDate" id="endDate" value="" class="" />
					</div>
				</div>
				<div class="dialog-form-row">
					<div class="form-label">
						<label for="users">Users</label>
					</div>
					<div class="form-field">
						<select name="users[]" id="users" multiple="multiple" size="3">
							<?php
                            foreach ($this->users as $user) :
                            ?>
							<option value="<?php echo $user['id']; ?>">
								<?php echo $user['first_name'] . " " . $user['last_name']; ?>
							</option>
							<?php endforeach; ?>
						</select>
					</div>
				</div>
				<div class="dialog-form-row">
					<div class="form-label-textarea">
						<label for="description">Description</label>
					</div>
					<div class="form-field">
						<textarea name="description" id="description" class=""></textarea>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
	<div id="dialog-delete-project" title="Remove project">
		<p>
			<span class="ui-icon ui-icon-alert"
				style="float: left; margin: 0 7px 20px 0;"></span>This item will be
			permanently deleted and cannot be recovered. Are you sure?
		</p>
	</div>
	<div class="spacer"></div>
</div>
<br />
