<style>
/*
a:link,a:visited {
	color: #0398CA;
}

span#zf-name {
	color: #91BE3F;
}

div#welcome {
	color: #FFFFFF;
	background-image: url(http://framework.zend.com/images/bkg_header.jpg);
	width: 600px;
	height: 400px;
	border: 2px solid #444444;
	overflow: hidden;
	text-align: center;
}

div#more-information {
	background-image:
		url(http://framework.zend.com/images/bkg_body-bottom.gif);
	height: 100%;
}*/
</style>
<div id="welcome">


	<div class="sign-in">
		<div class="signin-box">
		<div class="signin-header"><h2>Sign in </h2></div>
			<?php echo $this->form->setAction($this->url()); ?>
			<?php echo $this->error; ?>

			<!-- <form id="login" action="/index/login" method="post">
				<div class="username-div">
					<label for="username"><strong class="username-label">Username</strong></label>
					<input type="text" name="username" value="" id="username" />
				</div>
				<div class="password-div">
					<label for="password"><strong class="password-label">Password</strong></label>
					<input type="password" name="password" value="" id="password" />
				</div>

				<input type='submit' name='login' value='Login'>

			</form>
			 -->
		</div>
	</div>
</div>
<br /><br /><br /><br />
