<?php
$this->title = "Add Project";
$this->headTitle($this->title);
?>
<div class="subHeader">Add Project</div>

<dl class="zend_form">
	<dt id="project-name">
		<label for="projectName">Project Name:</label>
	</dt>
	<dd id="project-name-element">
		<input type="text" value="" id="projectName" name="projectName">
	</dd>
	<dt id="project-type">
		<label class="required" for="projectType">Project Type:</label>
	</dt>
	<dd id="project-type-element">
		<input type="text" value="" id="projectType" name="projectType">
	</dd>

	<dt id="project-type">
		<label class="required" for="projectType">Project Type:</label>
	</dt>
	<dd id="project-type-element">
		<input type="text" value="" id="projectType" name="projectType">
	</dd>


	<dt id="login-label">&nbsp;</dt>
	<dd id="login-element">
		<input type="submit" value="Add Project" id="addProject" name="addProject">
	</dd>
</dl>
