<?php
/* echo $this->headLink()->prependStylesheet($this->baseUrl() . '/static/dashboard/css/inettuts.css')
					  ->prependStylesheet($this->baseUrl() . '/static/dashboard/css/dashboard.css');
echo $this->headScript()->prependFile($this->baseUrl().'/static/dashboard/js/inettuts.js'); */

$this->title = "Projects";
$this->headTitle($this->title);
?>
<div class="subHeaderContainer">
	<div class="subHeader">My Dashboard</div>
</div>

	<div id="columns">

        <ul id="column1" class="column">
            <li class="widget color-sky" id="intro">
                <div class="widget-head">
                    <h3>Introduction</h3>
                </div>
                <div class="widget-content">
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam magna sem, fringilla in, commodo a, rutrum ut, massa. Donec id nibh eu dui auctor tempor. Morbi laoreet eleifend dolor. Suspendisse pede odio, accumsan vitae, auctor non, suscipit at, ipsum. Cras varius sapien vel lectus.</p>
                </div>
            </li>
        </ul>

        <ul id="column2" class="column">
            <li class="widget color-sky" id="quick">
                <div class="widget-head">
                    <h3>Quick Links</h3>
                </div>
                <div class="widget-content">
                    <div class="quicklink"><a href="<?php echo $this->baseUrl();?>/graphs/?pid=all&rid=all&gtype=st">Projects Story Reports</a></div>
                    <div class="quicklink"><a href="<?php echo $this->baseUrl();?>/graphs/?pid=all&rid=all&gtype=hr">Projects Hours Reports</a></div>
                    <div class="quicklink"><a href="<?php echo $this->baseUrl();?>/graphs/?pid=all&rid=all&gtype=td">Projects Trend Reports</a></div>
                </div>
            </li>
        </ul>

        <ul id="column3" class="row ui-sortable">
            <li class="widget color-sky" id="project">
                <div class="widget-head">
                    <h3>Project Details</h3>
                    <div class="dashboardFilterBox" id="dashboardProject">
                      <select class="dashboard-selectbox" name="dashboardProjectSelect" id="dashboardProjectSelect">
                            <?php foreach($this->projectViewType as $key => $value):?>                            	
                            	<option value="<?php echo $key;?>" ><?php echo $value;?></option>
                            <?php endforeach;?>                                               
                      </select>
                      <input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl();?>" />
                	</div>
                </div>
                <div class="widget-content">
                	<div class="table">
						<div class="rowHead">
							<div class="colsHead widthLargeHead">Project Name</div>
							<div class="colsHead widthMediumHead">Project Type</div>
							<div class="colsHead widthMediumHead">Current Release</div>
							<div class="colsHead widthMediumHead">Current Sprint</div>
							<div class="colsHead widthMediumHead">Sprint Start Date</div>
							<div class="colsHead widthMediumHead">Sprint End date</div>
							<div class="colsHead widthMediumHead">View Details</div>

						</div>
						<div id="recordContent">
							<?php echo $this->partial('dashboard/records.phtml', array('projects' => $this->projects));?>						
						</div>
						<div class="spacer"></div>
					</div>
                </div>
            </li>
        </ul>

    </div>



