<?php
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/static/dashboard/css/inettuts.css');
echo $this->headLink()->appendStylesheet($this->baseUrl() . '/static/dashboard/css/dashboard.css');
echo $this->headScript()->appendFile($this->baseUrl().'/static/dashboard/js/inettuts.js');
$this->title = "Projects";
$this->headTitle($this->title);
?>
<div class="subHeaderContainer">
	<div class="subHeader">My Dashboard</div>
</div>

	<div id="columns">

        <ul id="column1" class="column">
            <li class="widget color-sky" id="intro">
                <div class="widget-head">
                    <h3>Introduction</h3>
                </div>
                <div class="widget-content">
                    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam magna sem, fringilla in, commodo a, rutrum ut, massa. Donec id nibh eu dui auctor tempor. Morbi laoreet eleifend dolor. Suspendisse pede odio, accumsan vitae, auctor non, suscipit at, ipsum. Cras varius sapien vel lectus.</p>
                </div>
            </li>
        </ul>

        <ul id="column2" class="column">
            <li class="widget color-sky" id="quick">
                <div class="widget-head">
                    <h3>Quick Links</h3>
                </div>
                <div class="widget-content">
                    <div class="quicklink"><a href="/graphs#st">Projects Story Reports</a></div>
                    <div class="quicklink"><a href="/graphs#hr">Projects Hours Reports</a></div>
                    <div class="quicklink"><a href="/graphs#ln">Projects Trend Reports</a></div>
                </div>
            </li>
        </ul>

        <ul id="column3" class="row ui-sortable">
            <li class="widget color-sky" id="project">
                <div class="widget-head">
                    <h3>Project Details</h3>
                </div>
                <div class="widget-content">
                	<div class="table">
						<div class="rowHead">
							<div class="colsHead widthLargeHead">Project Name</div>
							<div class="colsHead widthMediumHead">Project Type</div>
							<div class="colsHead widthMediumHead">Current Release</div>
							<div class="colsHead widthMediumHead">Current Sprint</div>
							<div class="colsHead widthMediumHead">Sprint Start Date</div>
							<div class="colsHead widthMediumHead">Sprint End date</div>
							<div class="colsHead widthMediumHead">View Details</div>

						</div>

						<?php foreach ($this->projects as $project):?>
						 <div class="row" id="row_<?php echo $this->escape($project->dmsProjectsId);?>">
							<div class="cols widthLargeHead"><?php echo $this->escape($project->dmsProjectsName);?></div>
							<div class="cols widthMediumHead"><?php echo $this->escape($project->dmsProjecttypeName);?></div>
							<div class="cols widthMediumHead"><?php echo $this->escape($project->dmsReleasesName);?></div>
							<div class="cols widthMediumHead"><?php echo $this->escape($project->dmsSprintsName);?></div>
							<div class="cols widthMediumHead"><?php echo $this->escape($project->dmsSprintsStartDate);?></div>
							<div class="cols widthMediumHead"><?php echo $this->escape($project->dmsSprintsEndDate);?></div>
							<div class="colsAction "><a href="/projects/releases/<?php echo $this->escape($project->dmsProjectsId);?>">View</a></div>
						</div>
						<?php endforeach;?>
						<?php if(empty($this->projects)):?>
							<div class="elementContainer">No records available</div>
						<?php endif;?>
						<div class="spacer"></div>
					</div>
                </div>
            </li>
        </ul>

    </div>



