<?php
$this->title = "Projects";
$this->headTitle($this->title);
?>
<div class="subHeaderContainer">
	<div class="subHeader">My Dashboard</div>
</div>
<div class="table">
	<div class="rowHead">
		<div class="colsHead widthMediumHead">Project Name</div>
		<div class="colsHead widthMediumHead">Project Type</div>
		<div class="colsHead widthMediumHead">Objective</div>
		<div class="colsHead widthSmallHead">Current <br />Release</div>
		<div class="colsHead widthSmallHead">Current <br />Sprint</div>
		<div class="colsHead widthMediumHead">Sprint Start Date</div>
		<div class="colsHead widthMediumHead">Sprint End date</div>
		<div class="colsHead widthSmallHead">Action</div>

	</div>

	<?php foreach ($this->projects as $project):?>
	<div class="row" id="row_<?php echo $this->escape($project['id']);?>">
		<div class="cols widthMedium"><?php echo $this->escape($project['name']);?></div>
		<div class="cols widthMedium"><?php echo $this->escape($project['type']);?></div>
		<div class="cols widthMedium"><?php echo $this->escape($project['description']);?></div>
		<div class="cols widthSmall"><?php echo $this->escape($project['release']);?></div>
		<div class="cols widthSmall"><?php echo $this->escape($project['sprint']);?></div>
		<div class="cols widthMedium"><?php echo $this->escape($project['start_date']);?></div>
		<div class="cols widthMedium"><?php echo $this->escape($project['end_date']);?></div>
		<div class="colsAction widthSmall"><a href="/dashboard/release/<?php echo $this->escape($project['id']);?>">View</a></div>
	</div>
	<?php endforeach;?>
	<?php if(empty($this->projects)):?>
		<div class="elementContainer">No records available</div>
	<?php endif;?>
	<div class="spacer"></div>

</div>

