<?php
$this->title = "Projects";
$this->headTitle($this->title);
?>
<div class="subHeaderContainer">
	<div class="subHeader">My Dashboard</div>
</div>
<div class="table">
	<div class="rowHead">
		<div class="colsHead widthLargeHead">Release</div>
		<div class="colsHead widthMediumHead">Objective</div>
		<div class="colsHead widthMediumHead">Risks</div>
		<div class="colsHead widthMediumHead">Indicator</div>
		<div class="colsHead widthSmallHead">Start Date</div>
		<div class="colsHead widthSmallHead">End date</div>
		<div class="colsHead widthSmallHead">Total Hours</div>
		<div class="colsHead widthSmallHead">View Details</div>

	</div>

	<?php foreach ($this->projects as $project):?>
	<div class="row" id="row_<?php echo $this->escape($project['id']);?>">
		<div class="cols widthMedium"><?php echo $this->escape($project['release']);?></div>
		<div class="cols widthLarge"><?php echo $this->escape($project['objective']);?></div>
		<div class="cols widthMedium"><?php echo $this->escape($project['risk']);?></div>
		<div class="cols widthMedium"><?php echo $this->escape($project['start_date']);?></div>
		<div class="cols widthMedium"><?php echo $this->escape($project['end_date']);?></div>
		<div class="cols widthMedium">0</div>
		<div class="colsAction widthSmall"><a href="/dashboard/sprint/<?php echo $this->escape($project['id']);?>">View</a></div>
	</div>
	<?php endforeach;?>
	<?php if(empty($this->projects)):?>
		<div class="elementContainer">No records available</div>
	<?php endif;?>
	<div class="spacer"></div>

</div>

