<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Delivery Management System');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php //echo $this->baseUrl();exit;?>
<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/global.css')
							->prependStylesheet($this->baseUrl().'/css/redmond/jquery-ui-1.8.18.custom.css'); ?>

<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-1.7.1.min.js'); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/jquery-ui-1.8.18.custom.min.js'); ?>
<?php echo $this->headScript()->appendFile($this->baseUrl().'/js/global.js'); ?>

</head>
<body>
	<div id="container">
		<div id="header">
			<h2>Delivery Management System</h2>

		</div>
		<div id="topMenu">
		<?php echo $this->navigation()->menu(); ?>
		</div>
		<div id="homeContent">
		<div class="rightBlock"><?php echo $this->loggedInAs(); ?></div>
		<?php echo $this->layout()->content; ?>
		<div id="push"></div>

		</div>
		<div id="footer">Copyright 2012 - Abc. All Rights Reserved.</div>
	</div>
</body>
</html>
