<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Delivery Management Solution');
echo $this->doctype();
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<?php
// Do not break this appending in multiple echo statements.
// It will cause the css and js to load multiple times. Do not know the reason !!!
// Also be careful with the order in loading these files.
echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/graphs.css')
						->prependStylesheet($this->baseUrl() . '/static/dashboard/css/inettuts.css')
						->prependStylesheet($this->baseUrl() . '/static/dashboard/css/dashboard.css')
						->prependStylesheet($this->baseUrl() . '/css/global.css')
                        ->prependStylesheet($this->baseUrl() . '/css/simpletip.css')
                        ->prependStylesheet($this->baseUrl(). '/css/redmond/jquery-ui-1.8.18.custom.css');
?>
<?php echo $this->headScript()->prependFile($this->baseUrl() . '/js/graphs.js')
				->prependFile($this->baseUrl().'/static/dashboard/js/inettuts.js')
				->prependFile($this->baseUrl() . '/js/global.js')
                ->prependFile($this->baseUrl() . '/js/jquery.simpletip-1.3.1.min.js')
                ->prependFile($this->baseUrl(). '/js/jquery-ui-1.8.18.custom.min.js')
                ->prependFile($this->baseUrl() . '/js/jquery-1.7.1.min.js');

;
?>
</head>
<body>
	<div id="container" class="wrapper">
		<div id="header">
			<h2>Delivery Management Solution</h2>
		</div>
		<div id="topMenu">
			<?php echo $this->navigation()->menu(); ?>
		</div>
		<div id="homeContent">
			<div class="rightBlock">
				<?php echo $this->loggedInAs(); ?>
			</div>
			<?php echo $this->layout()->content; ?>
			<div id="push"></div>
		</div>
		<div class="push"></div>
	</div>
	<div class="footer"><p>Copyright 2012 - Accenture. All Rights Reserved.</p></div>
</body>
</html>
