<?php
//echo $this->headLink()->appendStylesheet($this->baseUrl() . '/css/graphs.css');
//echo $this->headScript()->prependFile($this->baseUrl().'/js/graphs.js');
$selected=''
?>

<div id="graphFilterContainer">
		 <div>
		 	<div class="seeGraph">&nbsp;</div>
		 	<div class="graphFilterBox graphFilterHead">Projects</div>
		 	<div class="graphFilterBox graphFilterHead">Releases</div>
		 	<div class="graphFilterBox graphFilterHead">Graph Type</div>
		 </div>
		 <div class="clear-both"></div>
	  	 <div id="graphFilterBlock">
    		    <div class="seeGraph">See graph by:</div>
                <div class="graphFilterBox" id="graphProject">
                      <select class="selectbox-class" name="lstLocation" id="graphProjectSelect">
                            <option value="all">All</option>
                            <?php foreach($this->projectname as $pname):?>
                            	<?php if($this->params['pid'] == $pname['dms_projects_id']){
                            		$selected=' selected=selected';
                            	}else{
                            		$selected='';
                            	}?>
                            	<option value="<?php echo $pname['dms_projects_id']?>" <?php echo $selected;?>><?php echo $pname['dms_projects_name']?></option>
                            <?php endforeach;?>
                      </select>
                </div>
                <div class="graphFilterBox" id="graphRelease">
                      <select class="selectbox-class" name="graphReleaseSelect" id="graphReleaseSelect">
                            <option value="all">All</option>
                            <?php foreach($this->releasename as $rname):?>
                            	<?php if($this->params['rid'] == $rname['dms_releases_id']){
                            		$selected =' selected=selected';
                            	}else{
                            		$selected='';
                            	}?>
                            	<option value="<?php echo $rname['dms_releases_id']?>" <?php echo $selected;?>><?php echo $rname['dms_releases_name']?></option>
                            <?php endforeach;?>
                      </select>
                </div>
                <div class="graphFilterBox" id="graphType">
                      <select class="selectbox-class" name="graphTypeSelect" id="graphTypeSelect">
                            <?php foreach($this->graphtype as $key=>$value):?>
                            <?php if($this->params['gtype'] == $key){
                            	$selected =' selected=selected';
                            }else{
                            	$selected='';
                            }?>
                            <option value="<?php echo $key?>" <?php echo $selected;?>><?php echo $value?></option>
                            <?php endforeach;?>
                      </select>
                </div>
                <input type="hidden" name="baseUrl" id="baseUrl" value="<?php echo $this->baseUrl();?>" />

    	 </div>
</div>
<br />
<br />

<a name="st" href="#"></a>
<div id="graphContainer" class="showgraph">

<img src="<?php echo $this->baseUrl().'/tmp/'.$this->renderGraph; ?>" alt="" />
</div>








