<?php
	//TODO move these code to model or helper
	$barDatax=array("Careers Portal","WDW","DCL","DLR");
	$barDatay=array(120,300,90,75);
	$barTitleArr = array(
		'x'=>"Projects --->",  // x axis title
		'y'=>"No. of Story Points --->", // y axis title
		'm'=>"Projectwise Story Points" // main title
	);
	$util = new Application_Model_Util();
	$fileName = $util->graphFileName('storygraph');
	$barGrph = $this->drawBarGraph($fileName,$barDatax,$barDatay,$barTitleArr); 
	
?>
<a name="st" href="#"></a>
THE BAR GRAPH DEPICTING PROJECT-STORIES MAPPING
<br /> 

<img src="<?php echo '../tmp/'.$barGrph; ?>" alt="The work begins here...." /> 







<hr/>
<a name="ln" href="#"></a>
THE LINE GRAPH DEPICTING PROJECT-STORIES,HRS,DEFECTS MAPPING
<br /> 
<?php 
	$lineDatax=array("Careers Portal","WDW","DCL","DLR");
	$lineDatay = array(
		"Stories"=> array("blue",array(28,19,18,23)),
		"Hours"=> array("red",array(14,18,33,29)),
		"Defects"=> array("green",array(14,20,15,25))
	);
	$lineTitleArr = array( 
		'm'=>"Projects Line Graph" // main title
	); // if reqd x and y titles can be set
	$fileName = $util->graphFileName('linegraph');
	$lnGrph = $this->drawLineGraph($fileName,$lineDatax,$lineDatay,$lineTitleArr);
?>

<img src="<?php echo '../tmp/'.$lnGrph; ?>" alt="The work begins here...." />








<hr/>
<a name="hr" href="#"></a>
THE BAR GRAPH DEPICTING PROJECT-HRS MAPPING

<?php
	$barDatax=array("Careers Portal","WDW","DCL","DLR");
	$barDatay=array(30,20,50,35);
	$barTitleArr = array(
		'x'=>"Projects --->",  // x axis title
		'y'=>"No. of Effort Hours --->", // y axis title
		'm'=>"Projectwise Effort" // main title
	);
	$fileName = $util->graphFileName('hoursgraph');
	$barGrph = $this->drawBarGraph($fileName,$barDatax,$barDatay,$barTitleArr); 
?>

<img src="<?php echo '../tmp/'.$barGrph; ?>" alt="The work begins here...." /> 

