<?php
$this->title = "My Dashboard";
$this->headTitle($this->title);
?>
<div class="subHeaderContainer">
	<div class="subHeader">My Dashboard</div>
	<div class="right-column">
		<select id="selectProject" name="selectProject">
			<option value="">All Projects</option>
			<?php foreach ($this->projects as $project) : ?>
			<option value="<?php echo $this->escape($project->id); ?>">
				<?php echo $this->escape($project->projectName); ?>
			</option>
			<?php endforeach; ?>
		</select>
	</div>
</div>
<?php if (empty($this->projectId)) { ?>
<div class="table">
	<div class="rowHead">
		<div class="colsHead widthLargeHead">Project Name</div>
		<div class="colsHead widthMediumHead">Project Type</div>
		<div class="colsHead widthMediumHead">Start Date</div>
		<div class="colsHead widthMediumHead">End date</div>
		<div class="colsHead widthMediumHead">Status</div>
		<div class="colsHead widthSmallHead">Action</div>
	</div>
	<?php foreach ($this->projects as $project) : ?>
	<div class="row" id="row_<?php echo $this->escape($project->id); ?>">
		<div class="cols widthLarge">
			<?php echo $this->escape($project->projectName); ?>
		</div>
		<div class="cols widthMedium">
			<?php echo $this->escape($project->projectType); ?>
		</div>
		<div class="cols widthMedium">
			<?php echo $this->escape($project->startDate); ?>
		</div>
		<div class="cols widthMedium">
			<?php echo $this->escape($project->endDate); ?>
		</div>
		<div class="cols widthMedium">In Progress</div>
		<div class="colsAction widthSmall">
			<a href="projects/edit">Edit</a>&nbsp;|&nbsp;<a
				href="home?projectId=<?php echo $this->escape($project->id); ?>">View</a>&nbsp;|&nbsp;<a
				href="#">Delete</a>
		</div>
	</div>
	<?php endforeach; ?>
	<div class="spacer"></div>
</div>
<?php } else { ?>
<div class="clear"></div>
<div class="projectHeader">
	<ul>
		<li>Project Name: XXXXXX XXXXXXXXX</li>
		<li>Start Date: XXXXXX</li>
		<li>End Date: XXXXXX</li>
	</ul>
</div>
<div class="table">
	<div class="rowHead">
		<div class="colsHead widthLargeHead">Release</div>
		<div class="colsHead widthMediumHead">Start Date</div>
		<div class="colsHead widthMediumHead">End date</div>
		<div class="colsHead widthMediumHead">Objective</div>
		<div class="colsHead widthMediumHead">Indicator</div>
		<div class="colsHead widthMediumHead">Status</div>
		<div class="colsHead widthSmallHead">Action</div>
	</div>
	<?php foreach ($this->projects as $project) : ?>
	<div class="row" id="row_<?php echo $this->escape($project->id); ?>">
		<div class="cols widthLarge">
			<?php echo $this->escape($project->projectName); ?>
		</div>
		<div class="cols widthMedium">
			<?php echo $this->escape($project->startDate); ?>
		</div>
		<div class="cols widthMedium">
			<?php echo $this->escape($project->endDate); ?>
		</div>
		<div class="cols widthMedium">XXXXXX</div>
		<div class="cols widthMedium">XXXXXX</div>
		<div class="cols widthMedium">In Progress</div>
		<div class="colsAction widthSmall">
			<a href="projects/releaseedit">Edit</a><br /> <a
				href="projects/releaseview">View</a><br /> <a href="#">Delete</a>
		</div>
	</div>
	<?php endforeach; ?>
	<div class="spacer"></div>
</div>
<?php } ?>
